<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class tracking_titles_seed extends Seeder
{
    public function run(): void
    {
        DB::table('tracking_titles')->insert([

            [
                'titles_dcn' => 'DCN-2025-001',
                'titles_title' => 'PROPOSED ORDINANCE ON WASTE MANAGEMENT',
                'titles_from' => 'OFFICE OF THE MAYOR',
                'titles_subject' => 'SOLID WASTE MANAGEMENT',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-002',
                'titles_title' => 'RESOLUTION SUPPORTING URBAN GREENING',
                'titles_from' => 'CITY ENVIRONMENT OFFICE',
                'titles_subject' => 'URBAN DEVELOPMENT',
                'document_type_id' => 2,
                'classifications_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-003',
                'titles_title' => 'ORDINANCE REGULATING STREET PARKING',
                'titles_from' => 'TRAFFIC MANAGEMENT OFFICE',
                'titles_subject' => 'TRAFFIC REGULATION',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-004',
                'titles_title' => 'RESOLUTION COMMENDING BARANGAY VOLUNTEERS',
                'titles_from' => 'BARANGAY AFFAIRS OFFICE',
                'titles_subject' => 'PUBLIC SERVICE',
                'document_type_id' => 2,
                'classifications_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-005',
                'titles_title' => 'ORDINANCE ESTABLISHING YOUTH CENTER',
                'titles_from' => 'YOUTH DEVELOPMENT OFFICE',
                'titles_subject' => 'YOUTH WELFARE',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-006',
                'titles_title' => 'RESOLUTION DECLARING HEALTH AWARENESS MONTH',
                'titles_from' => 'CITY HEALTH OFFICE',
                'titles_subject' => 'PUBLIC HEALTH',
                'document_type_id' => 2,
                'classifications_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-007',
                'titles_title' => 'ORDINANCE ON ANTI-NOISE REGULATION',
                'titles_from' => 'PUBLIC ORDER OFFICE',
                'titles_subject' => 'NOISE CONTROL',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-008',
                'titles_title' => 'RESOLUTION SUPPORTING SENIOR CITIZENS',
                'titles_from' => 'SOCIAL SERVICES OFFICE',
                'titles_subject' => 'SENIOR WELFARE',
                'document_type_id' => 2,
                'classifications_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-009',
                'titles_title' => 'ORDINANCE REGULATING FOOD ESTABLISHMENTS',
                'titles_from' => 'BUSINESS PERMITS OFFICE',
                'titles_subject' => 'FOOD SAFETY',
                'document_type_id' => 1,
                'classifications_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-010',
                'titles_title' => 'RESOLUTION AUTHORIZING PUBLIC CONSULTATION',
                'titles_from' => 'PLANNING OFFICE',
                'titles_subject' => 'PUBLIC PARTICIPATION',
                'document_type_id' => 2,
                'classifications_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 11–20 (also uppercase)

            [
                'titles_dcn' => 'DCN-2025-011',
                'titles_title' => 'ORDINANCE ON DISASTER PREPAREDNESS',
                'titles_from' => 'DISASTER RISK OFFICE',
                'titles_subject' => 'DISASTER MANAGEMENT',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-012',
                'titles_title' => 'RESOLUTION SUPPORTING LOCAL FARMERS',
                'titles_from' => 'AGRICULTURE OFFICE',
                'titles_subject' => 'AGRICULTURAL SUPPORT',
                'document_type_id' => 2,
                'classifications_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-013',
                'titles_title' => 'ORDINANCE REGULATING PUBLIC MARKETS',
                'titles_from' => 'MARKET ADMINISTRATION',
                'titles_subject' => 'MARKET REGULATION',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-014',
                'titles_title' => 'RESOLUTION DECLARING CITY CLEAN-UP DAY',
                'titles_from' => 'ENVIRONMENTAL OFFICE',
                'titles_subject' => 'CLEANLINESS DRIVE',
                'document_type_id' => 2,
                'classifications_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-015',
                'titles_title' => 'ORDINANCE ON PUBLIC TRANSPORT TERMINALS',
                'titles_from' => 'TRANSPORTATION OFFICE',
                'titles_subject' => 'PUBLIC TRANSPORT',
                'document_type_id' => 1,
                'classifications_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-016',
                'titles_title' => 'RESOLUTION SUPPORTING PERSONS WITH DISABILITY',
                'titles_from' => 'SOCIAL WELFARE OFFICE',
                'titles_subject' => 'PWD ASSISTANCE',
                'document_type_id' => 2,
                'classifications_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-017',
                'titles_title' => 'ORDINANCE ON FIRE SAFETY COMPLIANCE',
                'titles_from' => 'BUREAU OF FIRE PROTECTION',
                'titles_subject' => 'FIRE SAFETY',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-018',
                'titles_title' => 'RESOLUTION ENDORSING CULTURAL FESTIVAL',
                'titles_from' => 'CULTURAL AFFAIRS OFFICE',
                'titles_subject' => 'CULTURAL PROMOTION',
                'document_type_id' => 2,
                'classifications_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-019',
                'titles_title' => 'ORDINANCE REGULATING BUILDING SIGNAGES',
                'titles_from' => 'ENGINEERING OFFICE',
                'titles_subject' => 'BUILDING REGULATION',
                'document_type_id' => 1,
                'classifications_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titles_dcn' => 'DCN-2025-020',
                'titles_title' => 'RESOLUTION SUPPORTING EDUCATIONAL PROGRAMS',
                'titles_from' => 'CITY SCHOOLS DIVISION',
                'titles_subject' => 'EDUCATION SUPPORT',
                'document_type_id' => 2,
                'classifications_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}